server:
  servlet:
    context-path: /task-management/api/v1

spring:
  datasource:
    url: jdbc:derby:applicationdb;create=true
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    web: ERROR

springdoc:
  api-docs:
    path: /api-docs