server:
  servlet:
    context-path: /task-management

spring:
  datasource:
    url: jdbc:derby:applicationdb
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    web: ERROR

springdoc:
  api-docs:
    path: /api-docs