# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  java8:
    docker:
      - image: 'cimg/openjdk:8'

orbs:
  maven: circleci/maven@1.4.0
workflows:
  maven_test:
    jobs:
      - maven/test:
          command: '-X compile'
          executor: java8
